#!/bin/bash

OS=$(grep  -i ^id= /etc/os-release | cut -d '=' -f 2)

debian_pattern="^debian[_0-9]*$|^ubuntu[_0-9]*|linuxmint[_0-9]*$"


if [[ "$OS" -eq "ubuntu" || $OS =~ $debian_pattern ]]; then
	sudo apt-get install -y python3-pip
else
	sudo yum install -y python3-pip
fi

python3 -m pip install pandas==1.5.3 dash plotly pyarrow dash_bootstrap_components

aws s3 cp s3://cidaen-m14-capstone-dataset/social_network.parquet /tmp/
